FROM quay.io/jupyterhub/jupyterhub:latest

RUN apt update
RUN apt -y install python3-dev
RUN python3 -m pip install --no-cache-dir dockerspawner
RUN python3 -m pip install --no-cache-dir jupyterhub-nativeauthenticator

ENTRYPOINT ["jupyterhub", "-f", "/srv/jupyterhub/jupyterhub_config.py", "--log-level=DEBUG"]
